### ISSUE TITLE
Window Location

### ISSUE THREAD

**Issue by keegan-tennant** [RobotIlya/robotilya.github.io#1]
### Problem

When opening the window from Twitch, pop-up defaults to top left for me. Can we have this opening front and center?

### Scope

Anyone using the link.

### Examples

Video here: https://screenshot.click/02-31-ffwpu-6kkud.mp4

#### Expected vs Actual

Expected is the window opens where I'm looking (center screen) but actual being the window goes top left.

### Replication Steps

- Click image
- Watch as window goes to top left

### More Information

@RobotIlya @keyfer

**Comment by Christoflurp** [comment]
Is front and centre the best positioning? I feel like bottom right might be better because it won't overtake the streamers video feed.

Thoughts @RobotIlya

**Comment by RobotIlya-zz** [comment]
I was thinking bottom right as well as center would impact access to the feed and feel obnoxious.

**Comment by Christoflurp** [comment]
Closed on https://github.com/RobotIlya/robotilya.github.io/commit/413af8ff721babf79593ed6f5a887c9febf5840b
