### ISSUE TITLE
Checkout callback to close cart window.

### ISSUE THREAD

**Issue by Christoflurp** [RobotIlya/robotilya.github.io#2]
### Problem

Our buy button page will remain open when a user clicks the checkout button. We should have it so that when checkout is initiated, the buy button window closes and the new checkout maintains focus.

### Scope

All users.

### Examples

None

#### Expected vs Actual

Expected: When you click on checkout, the buy button page closes automatically to reduce window clutter.
Actual: It does not do this at this time. 

### Replication Steps

Click checkout.

### More Information

To be considered: If customer wants to return to the cart they won't be able to with this method. The checkout will be the only thing they can complete. If they're still on the streamers page they should be able to initialize the buy button window with the cached cart details though.

@RobotIlya @keegan-tennant

**Comment by RobotIlya-zz** [comment]
@keegan-tennant @BitterChris 
https://shopify.slack.com/archives/buy-button/p1488389451016324

**Comment by RobotIlya-zz** [comment]
@keyfer pulled a rabbit out of the proverbial hat and we're in business
