### ISSUE TITLE
[All Shops] One Random thing here is not doing other thing

### ISSUE THREAD

**Issue by cheronic** [RobotIlya/robotilya.github.io#5]
### Problem
One thing is not doing the other thing. 
### Scope
Affects only shops using x and y, under z conditions. 
### Examples

> order link(s)
In this order, I accidentally the whole thing
> Screenshot below shows that Dan is a good person:
[![alt](https://screenshot.click/21-51-f084r-xk2b9.png)](https://screenshot.click/21-51-f084r-xk2b9.png)

> order that does not work 

> odd parts

I ran a sql search to identify if Dan is responsible for doing the thing. Based on this, it SHOULD NOT be the case that he did the thing. 

```
select *
from is_dan_a_good_person
where world=earth
and Dan=human
ORDER BY Dan DESC
```

Splunk log of this happening at 5:00PM UTC ON March 456th. 

#### Expected vs Actual
Expected: I expect it to do the thing 

Actual: Did not do the thing. 

### Replication Steps

1. Dan went in and did the thing
2. efjhefhef
3. efjofejlf
4. foefohefoer

### More Information
Look related to:
https://github.com/RobotIlya/robotilya.github.io/issues/4
and 
https://github.com/RobotIlya/robotilya.github.io/issues/4

@keegan-tennant

**Comment by cheronic** [comment]
@RobotIlya have you considered that the thing intended to happen is not supposed to be a thing?

**Comment by RobotIlya-zz** [comment]
@cheronic Hey did you notice that this has changed to be a `codfish`:

** Happy fish**

On march 9000th merchant sent back a screenshot of x, doing y. Is this expected? 

New logs:

**Comment by cheronic** [comment]
This graph demonstrates x doing y on March 9000th:

![](https://screenshot.click/21-05-tbzc7-bjhpf.jpg)

@RobotIlya
